# NumPy  
NumPyはPythonで高速に数値計算を行う機能を提供するパッケージです。Pythoが科学計算分野で広く使われることに貢献したパッケージの一つといっても過言はないでしょう。  

## インストール  
macOSなら
```python
pip3 install numpy
```

## 基本的な使い方
標準モジュールと同様にNumPyを使うためにまずimportします。


In [21]:
import numpy

## 配列を作る  
Pythonにはすでにみてきたようにリストがありますが、NumPyではリストに似た"配列"と呼ばれるデータ構造を利用していきます。  
ここではPythonのリストからnumpy.array（配列)を作ります。  
一次元配列  

In [22]:
a = numpy.array([0,1,2,3])
print(a)

[0 1 2 3]


二次元配列  

In [11]:
b = numpy.array([[0,1,2],[3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


numpy.array([[0,1],[2,3,4]])といったサイズの異なる二次元配列を与えることもできますが、合う買いません。  

配列の次元は**shape属性**を見るとわかります。

In [12]:
print(".shape",a.shape)
print("b.shape",b.shape)

.shape (4,)
b.shape (2, 3)


要素数は**size属性**を見るとわかります。  

In [5]:
print("a.shape",a.size)
print("b.shape",b.size)

NameError: name 'a' is not defined

# 配列を作る関数  
numpy.arange()関数はリストの節で登場したrange()関数に似ています。  

In [13]:
#0から4までの整数をもつ配列を作る  
print(numpy.arange(5))

[0 1 2 3 4]


In [14]:
#1から9までの整数のうち奇数の配列を作る 
#(1から9まで2ステップずつ整数を取り出す)
print(numpy.arange(1,10,2))

[1 3 5 7 9]


reshape()メソッドをつかってから形を変更できます。また変形後の要素数は変形前の要素数と同じになる形でなければなりません。

In [15]:
print("6",numpy.arange(6))
print("2×3",numpy.arange(6).reshape(2,3))

6 [0 1 2 3 4 5]
2×3 [[0 1 2]
 [3 4 5]]


In [16]:
#　要素数6を要素3×3=9の形に変形はできない。
numpy.arange(6).reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

numpy.linspace()関数は指定した区間内から等間隔で値を取得します。

In [18]:
print(numpy.linspace(2.0,3.0,num=5,endpoint=False))

[2.  2.2 2.4 2.6 2.8]


間隔も同時に取得した場合はrestep=Trueを指定します。

In [25]:
a, step = numpy.linspace(2.0, 3.0, num=5,retstep = True)
print(a)
print(step)

[2.   2.25 2.5  2.75 3.  ]
0.25


numpy.ones()関数は配列の要素を1で埋めた配列を生成します。

In [28]:
#5つの1をもつ一次元配列
print(numpy.ones(5))

[1. 1. 1. 1. 1.]


In [29]:
print(numpy.ones((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [31]:
print(numpy.zeros(5))

[0. 0. 0. 0. 0.]


In [32]:
print(numpy.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [33]:
print(numpy.eye(2))

[[1. 0.]
 [0. 1.]]


In [35]:
a = numpy.array([2,4,6])
print(numpy.diag(a))

[[2 0 0]
 [0 4 0]
 [0 0 6]]


In [36]:
a = numpy.array([[2,4],[6,8]])
print("入力\n",a)
print("対角要素を取り出す\n",numpy.diag(a))

入力
 [[2 4]
 [6 8]]
対角要素を取り出す
 [2 8]


# データ型  
Pythonにint,float,strなどg