# NumPy  
NumPyはPythonで高速に数値計算を行う機能を提供するパッケージです。Pythoが科学計算分野で広く使われることに貢献したパッケージの一つといっても過言はないでしょう。  

## インストール  
macOSなら
```python
pip3 install numpy
```

## 基本的な使い方
標準モジュールと同様にNumPyを使うためにまずimportします。


In [109]:
import numpy

## 配列を作る  
Pythonにはすでにみてきたようにリストがありますが、NumPyではリストに似た"配列"と呼ばれるデータ構造を利用していきます。  
ここではPythonのリストからnumpy.array（配列)を作ります。  
一次元配列  

In [45]:
a = numpy.array([0,1,2,3])
print(a)

[0 1 2 3]


二次元配列  

In [46]:
b = numpy.array([[0,1,2],[3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


numpy.array([[0,1],[2,3,4]])といったサイズの異なる二次元配列を与えることもできますが、合う買いません。  

配列の次元は**shape属性**を見るとわかります。

In [47]:
print(".shape",a.shape)
print("b.shape",b.shape)

.shape (4,)
b.shape (2, 3)


要素数は**size属性**を見るとわかります。  

In [48]:
print("a.shape",a.size)
print("b.shape",b.size)

a.shape 4
b.shape 6


# 配列を作る関数  
numpy.arange()関数はリストの節で登場したrange()関数に似ています。  

In [49]:
#0から4までの整数をもつ配列を作る  
print(numpy.arange(5))

[0 1 2 3 4]


In [50]:
#1から9までの整数のうち奇数の配列を作る 
#(1から9まで2ステップずつ整数を取り出す)
print(numpy.arange(1,10,2))

[1 3 5 7 9]


reshape()メソッドをつかってから形を変更できます。また変形後の要素数は変形前の要素数と同じになる形でなければなりません。

In [51]:
print("6",numpy.arange(6))
print("2×3",numpy.arange(6).reshape(2,3))

6 [0 1 2 3 4 5]
2×3 [[0 1 2]
 [3 4 5]]


In [52]:
#　要素数6を要素3×3=9の形に変形はできない。
numpy.arange(6).reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

numpy.linspace()関数は指定した区間内から等間隔で値を取得します。

In [53]:
print(numpy.linspace(2.0,3.0,num=5,endpoint=False))

[2.  2.2 2.4 2.6 2.8]


間隔も同時に取得した場合はrestep=Trueを指定します。

In [54]:
a, step = numpy.linspace(2.0, 3.0, num=5,retstep = True)
print(a)
print(step)

[2.   2.25 2.5  2.75 3.  ]
0.25


numpy.ones()関数は配列の要素を1で埋めた配列を生成します。

In [55]:
#5つの1をもつ一次元配列
print(numpy.ones(5))

[1. 1. 1. 1. 1.]


In [56]:
print(numpy.ones((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [57]:
print(numpy.zeros(5))

[0. 0. 0. 0. 0.]


In [58]:
print(numpy.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [59]:
print(numpy.eye(2))

[[1. 0.]
 [0. 1.]]


In [60]:
a = numpy.array([2,4,6])
print(numpy.diag(a))

[[2 0 0]
 [0 4 0]
 [0 0 6]]


In [61]:
a = numpy.array([[2,4],[6,8]])
print("入力\n",a)
print("対角要素を取り出す\n",numpy.diag(a))

入力
 [[2 4]
 [6 8]]
対角要素を取り出す
 [2 8]


# データ型  
Pythonにint,float,strなどがあったように、NumPyにも基本的なデータ型があります。  
NumPyのデータ型を確認したり、指定する時にはdtype属性を通して操作を行います。  

よくでてくるデータ型にint64型、int32、float64、float32、boolがありますが、ここではそういうデータタイプがあるんだと言うことを頭の片隅に入れておく。もしdtype=objectとなっている場合は要素数が間違っているなど与えられたデータが間違っている可能性があります。  

In [62]:
# dtypeの確認
a = numpy.arange(5)
print("array=",a)
print("dtype=",a.dtype)

array= [0 1 2 3 4]
dtype= int64


In [63]:
# dtypeを設定して配列を作る
a = numpy.arange(5,dtype=float)
print("array=",a)
print("dtype=",a.dtype)

array= [0. 1. 2. 3. 4.]
dtype= float64


In [64]:
ao = numpy.array([[1],[2,3]])
print("array=",ao)
print("dtype=",ao.dtype)

array= [list([1]) list([2, 3])]
dtype= object


<ipython-input-64-55e5240cd3e6>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  ao = numpy.array([[1],[2,3]])


# 配列を用いた演算　　
ここまではNumPyの配列の作り方や要素の取り出し方をみてきました。リストやタプルの時はここで終わりでしたが、Numpy配列は先があります。  
Numpy配列に定義されているいくつかの演算をここではみていきます。
## 基本的な演算
配列と数値（int、float)の演算では配列の各要素に演算が適応されます。  

In [65]:
a = numpy.array([0,1,2,3])
print(a)

[0 1 2 3]


In [66]:
#aの要素に1をたす
print(a+1)

[1 2 3 4]


In [67]:
# aの各要素に1をたす
print(a+1)

[1 2 3 4]


In [68]:
# aの要素を2倍する
print(a*2)

[0 2 4 6]


配列同士の演算の時は配列のshapeによって使用方法が異なってくるため、慣れるのに少々時間が必要となってくるかもしれません。  
まず、二つの配列のshapeが
同じ時は各要素の演算が行われます。

In [71]:
a = numpy.array([1,2,3])
print("a=",a)

b = numpy.array([4,5,6])
print("b=",b)

a= [1 2 3]
b= [4 5 6]


In [72]:
#配列同士の和
print(a+b)

[5 7 9]


In [73]:
#配列同士の積
print(a*b)

[ 4 10 18]


## 比較  
配列同士の比較ができます。

In [75]:
a = numpy.array([1,2,3,4])
print(a)
b = numpy.array([1,2,2,1])
print(b)

[1 2 3 4]
[1 2 2 1]


In [76]:
#aとbの各要素が等しいか調べる
#Trueの時等しい
print(a == b)

[ True  True False False]


==には注意が必要です。1==1がtrueになるような共同を期待していても実際には上の例にもあるように配列を要素ごとの比較した結果が帰ってきます。配列の中身がすべて一緒の場合はTrueそれ以外の場合はFalseを返すようにするためにはnumpy.array_equal()関数を使います。

In [77]:
#配列aとbが等しいか調べる(すべての要素が同じかどうか)
print(numpy.array_equal(a,b))

False


In [79]:
c = numpy.array([1,2,3,4])
print(numpy.array_equal(a,c))

True


In [80]:
#配列aとbの各要素に対して,aの要素>bの要素が成り立つか確認する
print(a>b)

[False False  True  True]


In [81]:
print(a<b)

[False False False False]


# 配列のインデックスとスライス  
リストやタプルの要素へのアクセス方法と同様に、配列の要素を取得することができます。インデックスは0から始まることに注意しましょう。

In [84]:
a = numpy.array([1,3,5,7])
print(a)

[1 3 5 7]


In [85]:
# index=1（配列の3番目要素）を取得する
print(a[1])

3


二次元配列以上の多次元配列の場合にはインデックスを指定する順番、軸(axis)について
気をつける必要があります。

In [86]:
#　二次元配列
b = numpy.arange(6).reshape(2,3)
print("b=",b)
print("b.shape=",b.shape)

b= [[0 1 2]
 [3 4 5]]
b.shape= (2, 3)


In [88]:
#bの0番目の軸方向の一番目を取り出す
print("b[1]=",b[1])

#bの要素の軸方向の1番目かつ1番目の軸方向の一番目を取り出す
print("b[1,1]=",b[1,1])

b[1]= [3 4 5]
b[1,1]= 4


各軸のサイズについてはshapeで取得できる値を確認できます。

In [89]:
print(b.shape)

(2, 3)


(2,3)と帰ってきているのでaxis=0の方向はサイズ2、axis=1の方向はサイズ3といことが
わかります。  
スライスに関してもリスト、タプルと同様に[start:end]を指定します。

In [90]:
#　配列の1番目から2番目の要素を取り出す。
print(a[1:])

[3 5 7]


In [91]:
print(a[::-1])

[7 5 3 1]


In [92]:
#スライスした要素を更新することもできます。
print("before=",a)
a[2:]=numpy.array([10,14])
print("after=",a)

before= [1 3 5 7]
after= [ 1  3 10 14]


In [94]:
# 二次元配列の各軸についても同じようにスライスを取り出すことができます。  
b = numpy.arange(9).reshape(3,3)
print("b=",b)
print()
# aの右下2×2を取り出す。
print("b[1:, 1:]=",b[1:, 1:])

b= [[0 1 2]
 [3 4 5]
 [6 7 8]]

b[1:, 1:]= [[4 5]
 [7 8]]


これまでのスライスでは範囲指定して値を取り出してきたと思いますが、:を使うことにより範囲を指定せず全部取り出すことができます。

In [95]:
b = numpy.arange(6).reshape(2,3)
print("b=",b)
print()

#　ここではa[1,:]とa[1]は同じです。  
print("b[1,:]=",b[1,:])
print("b[1]=",b[1])
print()

#真ん中の列を取り出す。
print("b[:,1]=",b[:,1])

b= [[0 1 2]
 [3 4 5]]

b[1,:]= [3 4 5]
b[1]= [3 4 5]

b[:,1]= [1 4]


なお、:はNumPy配列独自の記法なのでこれまでのlistなどでは使えないことに気をつけてください。

## 特殊なインデックス  
配列へのアクセス方法は上記のインデックスやスライスを用いた方法の他に、条件にあう部分だけ取り出す、指定した順番に取り出すと行ったことができます。配列の要素の指定に配列を使うことでこれらの機能が利用できます。

In [96]:
a = numpy.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [97]:
# aの各要素が3で割り切れるかどうか(Trueなら割り切れる)
print(a % 3 ==0)

[ True False False  True False False  True False False  True False False
  True False False]


これをmaskという変数に代入するとします。

In [99]:
mask = (a % 3 == 0)
print(mask)

[ True False False  True False False  True False False  True False False
  True False False]


このmaskを用いると、配列aの各要素の中で3の倍数だけを取りだすことができます。

In [101]:
print(a[mask])

[ 0  3  6  9 12]


例えば、これらの要素を-1に変更してみます。

In [103]:
a[mask] = -1
print(a)

[-1  1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14]


上の例ではmaskをプログラム的に作成しました。その他に、整数のリスト（インデックスのリスト）を与えることもできます。

In [104]:
# 偶数リスト
lst = list(range(0,15,2))
print(a[lst])

[-1  2  4 -1  8 10 -1 14]


インデックスにはlistではなくNumPyのarrayも与えることができ同じように動きます。

In [111]:
print(a[numpy.arange(0,15,2)])

[-1  2  4 -1  8 10 -1 14]


このような特殊なインデックスをNumPyでは**fancy indexing**と呼んでいますがこの言葉自体は覚えなくても大丈夫です。

## NumPyの関数の適用　その1
NumPyにある関数はNumPy配列の各要素に呈して個別に適用するような関数が用意されています。

In [112]:
a = numpy.arange(1,5)
print(a)

[1 2 3 4]


numpy.tan()関数は配列aの各要素のy=tan(x)を求める関数です。類似の関数としては,numpy.sin()関数やnumpy.cos()関数が挙げられます。

In [113]:
print(numpy.tan(a))

[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


numpy.exp()関数は配列aの各要素のy=exp(x)を求める関数です。

In [115]:
print(numpy.log(a))

[0.         0.69314718 1.09861229 1.38629436]


## NumPyの関数の適用　その2
Numpy配列を使ってデータを表現した場合にそのデータの総和や最大最小といったデータの特徴を市レベル必要が生じる場合があります。  
ここではそのような時に使う関数の一部を紹介します。

In [116]:
a = numpy.array([1,2,3,4])
print(a)

[1 2 3 4]


In [117]:
print("総和",numpy.sum(a))
print("最大値",numpy.max(a))

総和 10
最大値 4


numpy.argmax()関数は最大値である要素のインデックス、numpy.aragmin()関数は最小である要素のインデックスを返します。つまりnumpy.argmax()関数で探索した番目の数値を取り出すとそれが最大値となります。numpy.argmin()関数はその逆です。

In [118]:
print("argmax=",numpy.argmax(a))
print("max=",a[numpy.argmax(a)])

argmax= 3
max= 4


以上の操作は配列のメソッドとしても利用することができます。

In [123]:
print("sum",a.sum())
print("max",a.max())
print("argmax",a.argmax())

sum 10
max 4
argmax 3


これらの集計関数もaxis方向を指定することでその軸方向への集計することができます。デフォルトでは結果は二次元配列の場合次元が一つ減った一次元配列となることに注意してください。

In [125]:
b = numpy.arange(6).reshape(2,3)
print("b=",b)
print("axis=0",b.sum(axis=0))
print("axis=1",b.sum(axis=1))
print("total",b.sum())

b= [[0 1 2]
 [3 4 5]]
axis=0 [3 5 7]
axis=1 [ 3 12]
total 15


keepdims = Trueを指定することで元の次元情報を保持してのその軸方向に集計を行います。

In [128]:
b0 = b.sum(axis=0,keepdims=True)
print("axis=0",b0)
print("axis=0 shape",b0.shape)
b1 = b.sum(axis=1,keepdims=True)
print("axis=1",b1)
print("axis=1 shape",b1.shape)


axis=0 [[3 5 7]]
axis=0 shape (1, 3)
axis=1 [[ 3]
 [12]]
axis=1 shape (2, 1)


## ソート関数  
最後に配列の要素をソートする方法を確認します。 

In [129]:
a = numpy.array([4,3,1,4,2])
print(a)

[4 3 1 4 2]


In [ ]:
配列の要素をソートする時はnumpy.sort()関数を利用します。

In [130]:
print(numpy.sort(a))

[1 2 3 4 4]


numpy.argsort()関数はソートした結果をインデックスで取得します。

In [132]:
print(numpy.argsort(a))

[2 4 1 0 3]


これは例えば最も小さい値は2番目の要素、次に小さい要素は4番目の要素という意味になります。  
先に説明した特殊なインデックスを用いるとnumpy.sort()関数と同じ結果が得られます。

In [133]:
mask = numpy.argsort(a)
a[mask]

array([1, 2, 3, 4, 4])

In [ ]:
## その他
ここではNumPyはいれt