# NumPy  
NumPyはPythonで高速に数値計算を行う機能を提供するパッケージです。Pythoが科学計算分野で広く使われることに貢献したパッケージの一つといっても過言はないでしょう。  

## インストール  
macOSなら
```python
pip3 install numpy
```

## 基本的な使い方
標準モジュールと同様にNumPyを使うためにまずimportします。


In [9]:
import numpy

## 配列を作る  
Pythonにはすでにみてきたようにリストがありますが、NumPyではリストに似た"配列"と呼ばれるデータ構造を利用していきます。  
ここではPythonのリストからnumpy.array（配列)を作ります。  
一次元配列  

In [10]:
a = numpy.array([0,1,2,3])
print(a)

[0 1 2 3]


二次元配列  

In [11]:
b = numpy.array([[0,1,2],[3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


numpy.array([[0,1],[2,3,4]])といったサイズの異なる二次元配列を与えることもできますが、合う買いません。  

配列の次元は**shape属性**を見るとわかります。

In [12]:
print(".shape",a.shape)
print("b.shape",b.shape)

.shape (4,)
b.shape (2, 3)


要素数は**size属性**を見るとわかります。  

In [5]:
print("a.shape",a.size)
print("b.shape",b.size)

NameError: name 'a' is not defined

# 配列を作る関数  
numpy.arange()関数はリストの節で登場したrange()関数に似ています。  

In [13]:
#0から4までの整数をもつ配列を作る  
print(numpy.arange(5))

[0 1 2 3 4]


In [14]:
#1から9までの整数のうち奇数の配列を作る 
#(1から9まで2ステップずつ整数を取り出す)
print(numpy.arange(1,10,2))

[1 3 5 7 9]


reshape()メソッドをつかってから形を変更できます。また変形後の要素数は変形前の要素数と同じになる形でなければなりません。

In [15]:
print("6",numpy.arange(6))
print("2×3",numpy.arange(6).reshape(2,3))

6 [0 1 2 3 4 5]
2×3 [[0 1 2]
 [3 4 5]]
