# NumPy  
NumPyはPythonで高速に数値計算を行う機能を提供するパッケージです。Pythoが科学計算分野で広く使われることに貢献したパッケージの一つといっても過言はないでしょう。  

## インストール  
macOSなら
```python
pip3 install numpy
```

## 基本的な使い方
標準モジュールと同様にNumPyを使うためにまずimportします。


In [2]:
import numpy

## 配列を作る  
Pythonにはすでにみてきたようにリストがありますが、NumPyではリストに似た"配列"と呼ばれるデータ構造を利用していきます。  
ここではPythonのリストからnumpy.array（配列)を作ります。  
一次元配列  

In [3]:
a = numpy.array([0,1,2,3])
print(a)

[0 1 2 3]


二次元配列  

In [4]:
b = numpy.array([[0,1,2],[3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


numpy.array([[0,1],[2,3,4]])といったサイズの異なる二次元配列を与えることもできますが、合う買いません。  

配列の次元は**shape属性**を見るとわかります。

In [5]:
print(".shape",a.shape)
print("b.shape",b.shape)

.shape (4,)
b.shape (2, 3)


要素数は**size属性**を見るとわかります。  

In [7]:
print("a.shape",a.size)
print("b.shape",b.size)

a.shape 4
b.shape 6


#　配列を作る関数  
numpy.arange()関数はリスト